### ISSUE TITLE
Ingest url duplication on restarting the docker container

### ISSUE THREAD

**Issue by skrispyb** [debloper/xplex#9]
When restarting the docker container the config file under /usr/local/nginx/conf/xplex.conf adds the ingest url configuration at the end of the file resulting in duplication of ingest url and it keeps on added every time you restart the docker container.

**Comment by debloper** [comment]
Caused due to the container run command included the ingests from ENV on each run; and we weren't sorting & filtering the ingests for uniqueness, leading to multiple copies of ingest entries.

The mechanism was updated since https://github.com/debloper/xplex/commit/c6535916c474b5c1bb2b75c5ebd6cf7186431f81. Ingests are no longer set with the ENVs, but with the webapp instead.

This keeps the process simple & easy; and obvious bugs like this are immediately noticeable.

```bash
# you can now try the latest 1.0.0 release version with:
docker run -d --name xplex -p 80:80 -p 1935:1935 xplex/xplex:1.0.0
```
